snowflake_tpch_demo:
  outputs:
    dev:
      type: snowflake
      account: almerls-bq47606
      user: KERLOSRADY1
      password: 01234567890kK@@
      role: ACCOUNTADMIN
      warehouse: DEV_WH
      database: snowflake_sample_data_demo
      schema: DBT_KZAKHARY
      threads: 6
  target: dev
