version: 2

models:
  - name: customer_revenue
    description: "Gold model: aggregated revenue by customer using TPCH formula SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))."
    columns:
      - name: customer_key
        description: "Customer primary key."
        tests:
          - not_null   # spec requires at least not_null; add 'unique' if you want 1 row per customer guaranteed

      - name: customer_name
        description: "Customer name."

      - name: revenue_amount
        description: "Total revenue per customer (rounded), computed from lineitem joined to orders."
