version: 2

models:
  - name: customer_revenue
    description: "Gold model: aggregated revenue by customer using TPCH formula SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))."
    columns:
      - name: customer_key
        description: "Customer primary key."
        tests:
          - not_null
          - unique
          
      - name: customer_name
        description: "Customer name."

      - name: revenue_amount
        description: "Total revenue per customer (rounded), computed from lineitem joined to orders."

  - name: nation_revenue
    description: "Aggregated revenue by nation using TPCH sample data."
    columns:
      - name: nation_name
        description: "Nation name (from TPCH nation table)."
        tests:
          - not_null

      - name: num_customers
        description: "Number of distinct customers in this nation."

      - name: total_revenue
        description: "Total revenue of all customers in that nation."
